name = "choire"
version = "1.0.7"
description = "ğŸ¶ Choire - gleam dependency tooling"
licences = ["Apache-2.0"]
repository = { type = "github", user = "daniellionel01", repo = "choire" }

[dependencies]
argv = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 2.0.0"
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_httpc = ">= 4.1.0 and < 5.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_stdlib = ">= 0.59.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
tom = ">= 2.0.0 and < 3.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
