name = "choire"
version = "1.0.2"

description = "ğŸ¶ Choire - gleam dependency tooling"
licences = ["Apache-2.0"]

repository = { type = "github", user = "daniellionel01", repo = "choire" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_httpc = ">= 4.1.0 and < 5.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
tom = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
